info:
  contact: {}
paths:
  /api/v1/albums:
    get:
      description: albums test
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: albums example
      tags:
      - albums
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
