info:
  contact: {}
paths:
  /albums:
    get:
      description: albums test
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: albums example
      tags:
      - albums
swagger: "2.0"
